config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "home#index"

  get 'home/index'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resources :articles do
    resources :comments, only: [:create]
  end
  resource :contacts, only: [:new, :create], path_names: {new: ''}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :delete_all
  
  validates :title, presence: true
  validates :text, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]
  before_action :load_article, only: [:show, :edit, :update, :destroy]

  def new
  end

  def create
    @article = Article.new article_params
    if @article.save
      redirect_to @article
    else
      render action: 'new'
    end
  end

  def index
    @articles = Article.order(id: :desc)
  end

  def show
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path, notice: "Delete success"
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

  def load_article
    @article ||= Article.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!, only: [:create]
  before_action :load_article, only: [:create]
    
  def create    
    @article.comments.create(comment_params)
    
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(author: current_user.username)
  end

  def load_article
    @article ||= Article.find(params[:article_id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
  end

  def create
    @contact = Contact.new(contact_params)

    unless @contact.save
      render action: 'new'
    end 
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms
  end

  def about
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/articles/_article.html.erb
<li>
<p>
    <%= link_to article.title, article_path(article) %> <br />
    <%= article.text %> <br />
    <%= link_to 'Show', article %> |
    <%= link_to 'Edit', edit_article_path(article) %> |
    <%= link_to 'Delete',
            article_path(article),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %>
</p>
</li>
<hr />

app/views/articles/_article_errors.html.erb
<% if @article && @article.errors.any? %>
  <p>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </p>
<% end %>

app/views/articles/_comment.html.erb
<li>
    <p>
    <h4><%= item.author %> said:</h4>
    <%= item.body %>
    </p>
</li>
<hr />

app/views/articles/edit.html.erb
<h2>Edit <%= params[:id] %> article</h2>
<%= form_for :article, url: article_path(@article), method: :put, html: {class: "form-horizontal", align: "center"} do |f| %>
  <%= render "article_errors" %>

  <p>
    <div class="form-group", align="center">
      <%= f.label :title, class: "col-md-4 control-label" %><br />
      <div class="col-md-12">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
  </p>

  <p>
    <div class="form-group", align="center">
      <%= f.label :text, class: "col-md-4 control-label" %><br />
      <div class="col-md-12">
        <%= f.text_area :text, class: "form-control" %>
      </div>
    </div>
  </p>

  <p>
    <%= f.submit "Save changes", class: "btn btn-default btn-primary" %>
  </p>
<% end %>

app/views/articles/index.html.erb
<h1>All articles</h1>
<ul>
  <%= render @articles %>
</ul>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= form_for :article, url: articles_path do |f| %>
  <%= render "article_errors" %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<h1>Article <%= @article.id %></h1>
<h2><%= @article.title %></h2>
<p>
  <%= @article.text %>
</p>
<hr />
<h3>Comments:</h3>

<ul>
  <%= render partial: "comment", collection: @article.comments, as: :item %>
</ul>

<h3>Add new comment</h3>

<p>
  <%= form_for([@article, @article.comments.build]) do |f| %>

    <p>
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit %>
    </p>
  <% end %>
</p>

app/views/contacts/_contact_errors.html.erb
<% if @contact && @contact.errors.any? %>
  <p>
    <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </p>
<% end %>

app/views/contacts/create.html.erb
<h1>ddd</h1>

app/views/contacts/new.html.erb
<h1>Contact us</h1>

<%= form_for :contact, url: contacts_path do |f| %>
  <%= render "contact_errors" %>

  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </p>

  <p>
    <%= f.submit 'Send message' %>
  </p>

<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= current_user.username %> | <%= link_to 'Sing Out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Sing In', new_user_session_path %>    
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h2>About</h2>

app/views/pages/terms.html.erb
<h2>Terms</h2>

app/views/terms/index.html.erb
<h2>Условия использования</h2>